
name: NodeJS React

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🙌 Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: ⚡️ Enable Corepack
        run: corepack enable

      - name: 👀 View Yarn Version
        run: echo yarn `yarn -v`

      - name: 🚚 Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 🧳 Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 📚 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🛠 Build project
        run: yarn build

      - name: 🚀 Deploy to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./build